// This file is generated by Sim IDX. Do not edit manually.
import { pgEnum, pgTable as table } from "drizzle-orm/pg-core";
import * as t from "drizzle-orm/pg-core";
import { db, types } from "@duneanalytics/sim-idx";

export const answerUpdated = table("answer_updated", {
  chainId: db.uint256('chain_id'),
  current: db.int256('current'),
  roundId: db.uint256('round_id'),
  updatedAt: db.uint256('updated_at'),
  txnHash: db.bytes32('txn_hash'),
  blockNumber: db.uint64('block_number'),
  blockTimestamp: db.uint64('block_timestamp'),
  aggregator: db.address('aggregator'),
})

export const externalLiquidation = table("external_liquidation", {
  chainId: db.uint256('chain_id'),
  vaultAddress: db.address('vault_address'),
  blockNumber: db.uint64('block_number'),
  blockTimestamp: db.uint64('block_timestamp'),
  txnHash: db.bytes32('txn_hash'),
  liquidator: db.address('liquidator'),
  violator: db.address('violator'),
  collateral: db.address('collateral'),
  repayAssets: db.uint256('repay_assets'),
  yieldBalance: db.uint256('yield_balance'),
  repayAssetsUsd: db.uint256('repay_assets_usd'),
  yieldBalanceUsd: db.uint256('yield_balance_usd'),
  collateralAmount: db.uint256('collateral_amount'),
  debtAmount: db.uint256('debt_amount'),
  collateralAmountUsd: db.uint256('collateral_amount_usd'),
  debtAmountUsd: db.uint256('debt_amount_usd'),
  liqLtv: db.uint256('liq_ltv'),
  creditReserved: db.uint256('credit_reserved'),
  creditReservedUsd: db.uint256('credit_reserved_usd'),
})

export const factoryHandleExternalLiquidation = table("factory_handle_external_liquidation", {
  chainId: db.uint256('chain_id'),
  factoryAddress: db.address('factory_address'),
  blockNumber: db.uint64('block_number'),
  blockTimestamp: db.uint64('block_timestamp'),
  txnHash: db.bytes32('txn_hash'),
})

export const factorySetCollateralVaultLiquidated = table("factory_set_collateral_vault_liquidated", {
  chainId: db.uint256('chain_id'),
  factoryAddress: db.address('factory_address'),
  collateralVault: db.address('collateral_vault'),
  creditVault: db.address('credit_vault'),
  debtVault: db.address('debt_vault'),
  underlyingCollateralVault: db.address('underlying_collateral_vault'),
  liquidatorAddress: db.address('liquidator_address'),
  blockNumber: db.uint64('block_number'),
  blockTimestamp: db.uint64('block_timestamp'),
  txnHash: db.bytes32('txn_hash'),
  creditReserved: db.uint256('credit_reserved'),
  debt: db.uint256('debt'),
  totalCollateral: db.uint256('total_collateral'),
  userOwnedCollateral: db.uint256('user_owned_collateral'),
  twyneLiqLtv: db.uint256('twyne_liq_ltv'),
  creditReservedUsd: db.uint256('credit_reserved_usd'),
  debtUsd: db.uint256('debt_usd'),
  totalCollateralUsd: db.uint256('total_collateral_usd'),
  userOwnedCollateralUsd: db.uint256('user_owned_collateral_usd'),
})

export const govSetCaps = table("gov_set_caps", {
  chainId: db.uint256('chain_id'),
  vaultAddress: db.address('vault_address'),
  blockNumber: db.uint64('block_number'),
  blockTimestamp: db.uint64('block_timestamp'),
  txnHash: db.bytes32('txn_hash'),
  newSupplyCap: db.uint16('new_supply_cap'),
  newBorrowCap: db.uint16('new_borrow_cap'),
})

export const govSetConfigFlags = table("gov_set_config_flags", {
  chainId: db.uint256('chain_id'),
  vaultAddress: db.address('vault_address'),
  blockNumber: db.uint64('block_number'),
  blockTimestamp: db.uint64('block_timestamp'),
  txnHash: db.bytes32('txn_hash'),
  newConfigFlags: db.uint32('new_config_flags'),
})

export const govSetFeeReceiver = table("gov_set_fee_receiver", {
  chainId: db.uint256('chain_id'),
  vaultAddress: db.address('vault_address'),
  blockNumber: db.uint64('block_number'),
  blockTimestamp: db.uint64('block_timestamp'),
  txnHash: db.bytes32('txn_hash'),
  newFeeReceiver: db.address('new_fee_receiver'),
})

export const govSetGovernorAdmin = table("gov_set_governor_admin", {
  chainId: db.uint256('chain_id'),
  vaultAddress: db.address('vault_address'),
  blockNumber: db.uint64('block_number'),
  blockTimestamp: db.uint64('block_timestamp'),
  txnHash: db.bytes32('txn_hash'),
  newGovernorAdmin: db.address('new_governor_admin'),
})

export const govSetHookConfig = table("gov_set_hook_config", {
  chainId: db.uint256('chain_id'),
  vaultAddress: db.address('vault_address'),
  blockNumber: db.uint64('block_number'),
  blockTimestamp: db.uint64('block_timestamp'),
  txnHash: db.bytes32('txn_hash'),
  newHookTarget: db.address('new_hook_target'),
  newHookedOps: db.uint32('new_hooked_ops'),
})

export const govSetInterestFee = table("gov_set_interest_fee", {
  chainId: db.uint256('chain_id'),
  vaultAddress: db.address('vault_address'),
  blockNumber: db.uint64('block_number'),
  blockTimestamp: db.uint64('block_timestamp'),
  txnHash: db.bytes32('txn_hash'),
  newFee: db.uint16('new_fee'),
})

export const govSetInterestRateModel = table("gov_set_interest_rate_model", {
  chainId: db.uint256('chain_id'),
  vaultAddress: db.address('vault_address'),
  blockNumber: db.uint64('block_number'),
  blockTimestamp: db.uint64('block_timestamp'),
  txnHash: db.bytes32('txn_hash'),
  newInterestRateModel: db.address('new_interest_rate_model'),
})

export const govSetLiquidationCoolOffTime = table("gov_set_liquidation_cool_off_time", {
  chainId: db.uint256('chain_id'),
  vaultAddress: db.address('vault_address'),
  blockNumber: db.uint64('block_number'),
  blockTimestamp: db.uint64('block_timestamp'),
  txnHash: db.bytes32('txn_hash'),
  newCoolOffTime: db.uint16('new_cool_off_time'),
})

export const govSetLtv = table("gov_set_ltv", {
  chainId: db.uint256('chain_id'),
  vaultAddress: db.address('vault_address'),
  blockNumber: db.uint64('block_number'),
  blockTimestamp: db.uint64('block_timestamp'),
  txnHash: db.bytes32('txn_hash'),
  collateral: db.address('collateral'),
  borrowLtv: db.uint16('borrow_ltv'),
  liquidationLtv: db.uint16('liquidation_ltv'),
  initialLiquidationLtv: db.uint16('initial_liquidation_ltv'),
  targetTimestamp: db.uint48('target_timestamp'),
  rampDuration: db.uint32('ramp_duration'),
})

export const govSetMaxLiquidationDiscount = table("gov_set_max_liquidation_discount", {
  chainId: db.uint256('chain_id'),
  vaultAddress: db.address('vault_address'),
  blockNumber: db.uint64('block_number'),
  blockTimestamp: db.uint64('block_timestamp'),
  txnHash: db.bytes32('txn_hash'),
  newDiscount: db.uint16('new_discount'),
})

export const positionSnapshot = table("position_snapshot", {
  chainId: db.uint256('chain_id'),
  vaultAddress: db.address('vault_address'),
  underlyingCollateralVault: db.address('underlying_collateral_vault'),
  creditVault: db.address('credit_vault'),
  debtVault: db.address('debt_vault'),
  maxRelease: db.uint256('max_release'),
  maxRepay: db.uint256('max_repay'),
  totalAssetsDepositedOrReserved: db.uint256('total_assets_deposited_or_reserved'),
  userOwnedCollateral: db.uint256('user_owned_collateral'),
  twyneLiqLtv: db.uint256('twyne_liq_ltv'),
  canLiquidate: t.boolean('can_liquidate'),
  isExternallyLiquidated: t.boolean('is_externally_liquidated'),
  maxReleaseUsd: db.uint256('max_release_usd'),
  maxRepayUsd: db.uint256('max_repay_usd'),
  totalAssetsDepositedOrReservedUsd: db.uint256('total_assets_deposited_or_reserved_usd'),
  userOwnedCollateralUsd: db.uint256('user_owned_collateral_usd'),
  blockNumber: db.uint64('block_number'),
  blockTimestamp: db.uint64('block_timestamp'),
  logIndex: db.uint256('log_index'),
  creditVaultTotalAssets: db.uint256('credit_vault_total_assets'),
  creditVaultTotalBorrows: db.uint256('credit_vault_total_borrows'),
  state: t.text('state'),
  txType: t.text('tx_type'),
})

export const preExternalLiquidation = table("pre_external_liquidation", {
  chainId: db.uint256('chain_id'),
  vaultAddress: db.address('vault_address'),
  blockNumber: db.uint64('block_number'),
  blockTimestamp: db.uint64('block_timestamp'),
  txnHash: db.bytes32('txn_hash'),
  violator: db.address('violator'),
  collateral: db.address('collateral'),
  collateralAmount: db.uint256('collateral_amount'),
  debtAmount: db.uint256('debt_amount'),
  collateralAmountUsd: db.uint256('collateral_amount_usd'),
  debtAmountUsd: db.uint256('debt_amount_usd'),
  eulerLiqLtv: db.uint256('euler_liq_ltv'),
  twyneLiqLtv: db.uint256('twyne_liq_ltv'),
  creditReserved: db.uint256('credit_reserved'),
  creditReservedUsd: db.uint256('credit_reserved_usd'),
  twyneMaxLiqLtv: db.uint256('twyne_max_liq_ltv'),
  twyneSafetyBuffer: db.uint256('twyne_safety_buffer'),
})

export const vaultBorrow = table("vault_borrow", {
  chainId: db.uint256('chain_id'),
  vaultAddress: db.address('vault_address'),
  targetAmount: db.uint256('target_amount'),
  receiver: db.address('receiver'),
  borrowerAddress: db.address('borrower_address'),
  blockNumber: db.uint64('block_number'),
  blockTimestamp: db.uint64('block_timestamp'),
  txnHash: db.bytes32('txn_hash'),
  logIndex: db.uint256('log_index'),
})

export const vaultCreated = table("vault_created", {
  chainId: db.uint256('chain_id'),
  vaultAddress: db.address('vault_address'),
  creator: db.address('creator'),
  factory: db.address('factory'),
  blockNumber: db.uint64('block_number'),
  blockTimestamp: db.uint64('block_timestamp'),
  txnHash: db.bytes32('txn_hash'),
  asset: db.address('asset'),
  intermediateVault: db.address('intermediate_vault'),
  underlyingCollateralVault: db.address('underlying_collateral_vault'),
  targetAsset: db.address('target_asset'),
  targetVault: db.address('target_vault'),
  twyneLiqLtv: db.uint256('twyne_liq_ltv'),
  twyneVaultManager: db.address('twyne_vault_manager'),
  version: db.uint256('version'),
})

export const vaultDeposit = table("vault_deposit", {
  chainId: db.uint256('chain_id'),
  vaultAddress: db.address('vault_address'),
  amount: db.uint256('amount'),
  userAddress: db.address('user_address'),
  blockNumber: db.uint64('block_number'),
  blockTimestamp: db.uint64('block_timestamp'),
  txnHash: db.bytes32('txn_hash'),
  logIndex: db.uint256('log_index'),
})

export const vaultDepositUnderlying = table("vault_deposit_underlying", {
  chainId: db.uint256('chain_id'),
  vaultAddress: db.address('vault_address'),
  amount: db.uint256('amount'),
  userAddress: db.address('user_address'),
  blockNumber: db.uint64('block_number'),
  blockTimestamp: db.uint64('block_timestamp'),
  txnHash: db.bytes32('txn_hash'),
  logIndex: db.uint256('log_index'),
})

export const vaultMetrics = table("vault_metrics", {
  chainId: db.uint256('chain_id'),
  vaultAddress: db.address('vault_address'),
  totalAssets: db.uint256('total_assets'),
  totalAssetsUsd: db.uint256('total_assets_usd'),
  totalBorrows: db.uint256('total_borrows'),
  totalBorrowsUsd: db.uint256('total_borrows_usd'),
  asset: db.address('asset'),
  interestRate: db.uint256('interest_rate'),
  symbol: t.text('symbol'),
  name: t.text('name'),
  decimals: db.uint256('decimals'),
  blockNumber: db.uint256('block_number'),
  blockTimestamp: db.uint256('block_timestamp'),
})

export const vaultRepay = table("vault_repay", {
  chainId: db.uint256('chain_id'),
  vaultAddress: db.address('vault_address'),
  repayAmount: db.uint256('repay_amount'),
  userAddress: db.address('user_address'),
  blockNumber: db.uint64('block_number'),
  blockTimestamp: db.uint64('block_timestamp'),
  txnHash: db.bytes32('txn_hash'),
  logIndex: db.uint256('log_index'),
})

export const vaultTeleport = table("vault_teleport", {
  chainId: db.uint256('chain_id'),
  vaultAddress: db.address('vault_address'),
  toDeposit: db.uint256('to_deposit'),
  toBorrow: db.uint256('to_borrow'),
  userAddress: db.address('user_address'),
  blockNumber: db.uint64('block_number'),
  blockTimestamp: db.uint64('block_timestamp'),
  txnHash: db.bytes32('txn_hash'),
  logIndex: db.uint256('log_index'),
})

export const vaultWithdraw = table("vault_withdraw", {
  chainId: db.uint256('chain_id'),
  vaultAddress: db.address('vault_address'),
  amount: db.uint256('amount'),
  receiver: db.address('receiver'),
  userAddress: db.address('user_address'),
  blockNumber: db.uint64('block_number'),
  blockTimestamp: db.uint64('block_timestamp'),
  txnHash: db.bytes32('txn_hash'),
  logIndex: db.uint256('log_index'),
})
